#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.04 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfffe;
constexpr uint24_t FX_DATA_BYTES = 453;

constexpr uint24_t Theme = 0x000000;
constexpr uint24_t Theme_Len = 0x0000D9;
constexpr uint24_t fxLogo = 0x0000DB;
